### ISSUE TITLE
-neuron -run option results in frozen NEURON GUI

### ISSUE THREAD

**Issue by JustasB** [NeuroML/jNeuroML#27]
This happens to me with any model. Tried on Mac OS.

Typing:

```
jnml LEMS_FILE.xml -neuron -run
```

Opens up NEURON GUI, runs the simulation, graphs show up. However, I cannot change anything. The GUI appears to be unresponsive (no right click menu, no main menu dropdowns). When resizing the chart (dragging the lower right corner), it looks like this: 

![screen shot 2015-07-20 at 4 37 48 pm](https://cloud.githubusercontent.com/assets/10732358/8790032/cedf3be4-2efd-11e5-8ec3-bd24212a5fbb.png)

When I run neuron separately, this problem is not present. Only with jnml -neuron -run.

**Comment by pgleeson** [comment]
Yes, a known issue... It's down to the fact that the main Neuron process is running inside Java since the console output needs to be caught and displayed, see https://github.com/NeuroML/org.neuroml.export/blob/development/src/main/java/org/neuroml/export/neuron/NeuronWriter.java#L109. This is fine when the -nogui option is selected, the main process just terminates at the end. Without -nogui though, it impacts the GUI elements associated with the main process, and they're unresponsive. 

A solution would be (as is used in neuroConstruct) to spawn a new terminal (gnome terminal, mac terminal or CMD in win...) and run the main Neuron process inside that. jnml can exit and the console output is captured and the GUI elements are responsive.

**Comment by cheelee** [comment]
Wouldn't running the Neuron process in a separate Java thread take care of this issue? The Java GUI threads only get stalled like this if unnecessarily heavy compute workloads get invoked (usually by accident) inside a GUI thread (the event loop) instead of a regular Java thread.

**Comment by JustasB** [comment]
As a workaround, the following seems to work:

1. ```jnml LEMS_FILE.xml -neuron -run```
2. Once NEURON opens, CTRL+C to close NEURON
3. Run ```nrngui -python LEMS_FILE_nrn.py```

The NEURON GUI is not frozen after launching it with Step 3.

**Comment by pgleeson** [comment]
Best way to use this is either: 

    1. jnml LEMS_FILE.xml -neuron
    2. nrnivmodl
    3. nrngui LEMS_FILE_nrn.py

or just:

    jnml LEMS_FILE.xml -neuron -nogui -run

This generates hoc/mod, compiles mod, runs the file, saves the data and closes. If you want to rerun, look at plots, just do:

    nrngui LEMS_FILE_nrn.py
